<a href="https://colab.research.google.com/github/vamseeky/finance/blob/master/compoundreturns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
prices_spxt = [3769.44, 3821.6, 4278.66, 5212.76, 4984.22, 6553.57] #end of year index level of S&P500 total return index 2014 to 2019

In [16]:
prices_spxt[1:] #shows the elements from index 1 (note python starts at index 0)

[3821.6, 4278.66, 5212.76, 4984.22, 6553.57]

In [17]:
prices_spxt[:-1] #shows elements before the previous one

[3769.44, 3821.6, 4278.66, 5212.76, 4984.22]

In [18]:
prices_spxt[1:]/prices_spxt[:-1]-1 #this gives an error because python cannot divide arrays .. need to use numpy

TypeError: ignored

Using numpy libraries

In [20]:
import numpy as np
prices_spxt_a = np.array(prices_spxt) #we are now converting python array into numpy array
prices_spxt_a

array([3769.44, 3821.6 , 4278.66, 5212.76, 4984.22, 6553.57])

In [21]:
prices_spxt_a[1:]/prices_spxt_a[:-1]-1 #now we should be able to see the yearly total returns of S&P500

array([ 0.0138376 ,  0.11959912,  0.21831601, -0.04384242,  0.31486371])

Using Pandas


In [25]:
import pandas as pd
prices_spxt_df = pd.DataFrame(prices_spxt)
prices_spxt_df

0
0  3769.44
1  3821.60
2  4278.66
3  5212.76
4  4984.22
5  6553.57

In [35]:
prices_spxt_df.pct_change() #using built-in % change function in pandas

0
0       NaN
1  0.013838
2  0.119599
3  0.218316
4 -0.043842
5  0.314864

In [34]:
prices_spxt_df.iloc[1:].values/prices_spxt_df.iloc[:-1].values-1 #using iloc and values to calculate 

array([[ 0.0138376 ],
       [ 0.11959912],
       [ 0.21831601],
       [-0.04384242],
       [ 0.31486371]])

In [33]:
prices_spxt_df/prices_spxt_df.shift(1)-1 #using the shift() function

0
0       NaN
1  0.013838
2  0.119599
3  0.218316
4 -0.043842
5  0.314864